[package]
name = "hello_world"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
gwasm-api = { git="https://github.com/golemfactory/gwasm-runner.git" }
